--- #YAML:1.0
name:                Template-Plugin-HighlightPerl
version:             0.01
abstract:            Template Toolkit plugin which 
license:             ~
author:              
    - Stephen A Sykes <stephen@stephensykes.us>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Syntax::Highlight::Perl:       1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
